# Generated by Django 5.0.1 on 2024-11-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('round_type', models.CharField(choices=[('HR', 'HR Round'), ('COMM', 'Communication Round'), ('TECH', 'Technical Round'), ('APT', 'Aptitude Round')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
    ]
